import os
import subprocess
import sys
import time
import uuid

import docker
import pexpect
from docker.errors import ContainerError, ImageNotFound

from libkit.language_configs import get_language_config

sys.path.append(os.path.dirname(os.path.abspath(__file__)))


def truncate_msg(result_message, command, truncate=2000, bar_truncate=20):
    lines = result_message.splitlines()
    lines = [x for x in lines if len(x.strip()) > 0]
    # Stores line indices that look like progress bars.
    bar_lines = list()
    for i in range(len(lines)):
        line = lines[i]
        if (
            line.strip().startswith("\x1b[")
            or line.count("\x1b[") >= 2
            or line.count("█") >= 2
            or "━━━━━" in line
        ):
            bar_lines.append(i)
    if len(bar_lines) > bar_truncate:
        for i in range(len(lines)):
            if i in bar_lines[:-bar_truncate]:
                lines[i] = ""
    lines = [x for x in lines if len(x) > 0]

    result_message = "\n".join(lines)
    res = result_message
    # Handle overly long output.
    if len(result_message) > truncate * 3:
        res = f"Running `{command}`...\nThe output is too long, so we've truncated it to show you the first and last 5000 characters.\n"
        res += (
            result_message[: truncate * 3]
            + "\n...[Truncation]...\n"
            + result_message[-truncate * 3 :]
        )
    elif len(result_message.split(" ")) > truncate:
        res = f"Running `{command}`...\nThe output is too long, so we've truncated it to show you the first and last 2500 words.\n"
        res += (
            " ".join(result_message.split(" ")[:truncate])
            + "\n...[Truncation]...\n"
            + " ".join(result_message.split(" ")[-truncate:])
        )

    return res


def delete_dangling_image():
    dangling_images = (
        subprocess.check_output('docker images --filter "dangling=true" -q', shell=True)
        .decode("utf-8")
        .strip()
    )
    if dangling_images:
        rmi_cmd = f"docker rmi {dangling_images}"
        # print("📋 Running command:", rmi_cmd)
        # Use DEVNULL instead of PIPE to avoid file descriptor leaks.
        subprocess.run(
            rmi_cmd, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
        )


def compare_versions(version1, version2):
    parts1 = version1.split(".")
    parts2 = version2.split(".")
    max_len = max(len(parts1), len(parts2))
    parts1.extend(["0"] * (max_len - len(parts1)))
    parts2.extend(["0"] * (max_len - len(parts2)))
    for part1, part2 in zip(parts1, parts2):
        part1 = int(part1)
        part2 = int(part2)
        if part1 > part2:
            return 1
        elif part1 < part2:
            return -1
    # If all parts are equal, the versions are the same.
    return 0


class Env:
    def __init__(
        self,
        namespace,
        language,
        repo_full_name,
        root_path,
        save_mode="none",
        use_repo_dockerfile=False,
        repo_dockerfile_path=None,
        dockerfile_content=None,
        use_uv=False,
    ):
        """
        namespace: e.g. a base image tag like python:3.11
        save_mode: 'none' - do not save; 'dockerfile' - save Dockerfile and files; 'image' - save as an image
        use_repo_dockerfile: whether to use the repository's own Dockerfile
        repo_dockerfile_path: absolute path to the repo Dockerfile (when using the repo Dockerfile)
        dockerfile_content: Dockerfile content generated by SetupAgent (optional)
        use_uv: whether to use uv as the Python package manager
        language_config: language configuration object used to generate Dockerfile
        """

        self.namespace = namespace
        self.client = docker.from_env(timeout=600)
        self.container = None
        self.shell = None
        self.commands = list()
        self.full_name = repo_full_name
        self.root_path = root_path
        self.save_mode = save_mode
        self.use_repo_dockerfile = use_repo_dockerfile
        self.repo_dockerfile_path = repo_dockerfile_path
        self.dockerfile_content = dockerfile_content

        self.use_uv = use_uv
        self.language = language

        # Language config: always fetch via get_language_config.
        # For Java, create_dockerfile updates the config dynamically based on project files.
        self.language_config = get_language_config(self.language, use_uv=self.use_uv)

        # Generate a unique container name to support parallel execution.
        self.container_name = self._generate_unique_container_name()

    def __enter__(self):
        """Context manager entry."""
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit - ensures cleanup."""
        try:
            self.stop_container()
        except Exception as e:
            print(f"⚠️  Error during context manager cleanup: {e}")
        finally:
            # Close the Docker client to release file descriptors.
            if self.client:
                try:
                    self.client.close()
                    self.client = None
                except Exception as e:
                    print(f"⚠️  Error closing Docker client: {e}")
        # Do not suppress exceptions; let them propagate.
        return False

    def get_standard_container_name(self):
        return self.full_name.lower().replace("/", "_").replace("-", "_")

    def _generate_unique_container_name(self):
        """Generate a unique container name to support parallel execution."""
        base_name = self.get_standard_container_name()
        unique_id = uuid.uuid4().hex[:8]
        return f"rat_{base_name}_{unique_id}"

    def create_shell(self):
        if self.container:
            # 1. Clean up the old shell (if any).
            if self.shell:
                try:
                    if self.shell.isalive():
                        self.shell.close(force=True)
                except Exception as e:
                    print(f"⚠️  Error closing old shell: {e}")
                finally:
                    self.shell = None

            # 2. Create a new shell.
            command = f"docker exec -it {self.container.id} /bin/bash"
            print("📋 Running command:", command)

            temp_shell = None
            try:
                # Use poll() instead of select() to avoid the >1024 file descriptor limit.
                temp_shell = pexpect.spawn(command, use_poll=True)
                # self.shell.expect([r'\$ ', r'# '], timeout=600)
                temp_shell.expect([r"[$#]"], timeout=600)

                # If using uv, ensure PATH includes uv's install path.
                if self.use_uv:
                    temp_shell.sendline('export PATH="/root/.cargo/bin:$PATH"')
                    temp_shell.expect([r"[$#]"], timeout=10)

                # 3. Only assign to self.shell after success.
                self.shell = temp_shell

            except Exception as e:
                # 4. If it fails, clean up the temporary shell.
                print(f"❌ Failed to create shell: {e}")
                if temp_shell:
                    try:
                        temp_shell.close(force=True)
                    except:
                        pass
                raise Exception(f"Failed to create shell: {e}")
        else:
            raise Exception("Container not started. Call start_container() first.")

    def recreate_shell(self, target_dir="/repo"):
        """
        Recreate the Shell session.

        When the Shell becomes unavailable (e.g. due to timeouts), close the old
        connection and create a new Shell. After recreation, it automatically
        switches to the target working directory.

        Args:
            target_dir: Directory to switch to after recreation; defaults to /repo.

        Returns:
            bool: Whether recreation succeeded.
        """
        print("🔄 Shell session unavailable; recreating...")

        try:
            # 1. Close the old shell (if any and still alive).
            if self.shell:
                try:
                    if self.shell.isalive():
                        self.shell.close(force=True)
                        print("   ✓ Closed old Shell")
                except Exception as e:
                    print(f"   ⚠️  Error closing old Shell: {e}")
                finally:
                    self.shell = None

            # 2. Create a new shell.
            self.create_shell()
            print("   ✓ Created new Shell")

            # 3. Switch to the target working directory.
            if target_dir and target_dir != "/root":
                try:
                    self.shell.sendline(f"cd {target_dir}")
                    self.shell.expect([r"root@.*:.*# ", r"[$#]"], timeout=5)
                    print(f"   ✓ Switched to directory: {target_dir}")
                except Exception as e:
                    print(f"   ⚠️  Failed to switch directory: {e}; using default")
                    # If switching fails, try /repo.
                    if target_dir != "/repo":
                        try:
                            self.shell.sendline("cd /repo")
                            self.shell.expect([r"root@.*:.*# ", r"[$#]"], timeout=5)
                            print("   ✓ Switched to /repo")
                        except:
                            print("   ⚠️  Failed to switch to /repo; keeping current")

            print("✅ Shell recreation succeeded")
            return True

        except Exception as e:
            print(f"❌ Shell recreation failed: {e}")
            return False

    def create_dockerfile(self):
        dockerfile_path = f"{self.root_path}/input/repo/{self.full_name}/Dockerfile"

        # If dockerfile_content is provided (generated by SetupAgent), use it directly.
        if self.dockerfile_content:
            print("✅ Using Dockerfile generated by SetupAgent")
            with open(dockerfile_path, "w") as f:
                f.write(self.dockerfile_content)
            return f"{self.root_path}/input/repo/{self.full_name}"

        # Fallback: generate via LanguageConfig (for non-Rust projects or when SetupAgent fails).
        print("⚠️  Falling back to LanguageConfig template for Dockerfile generation")

        # Extract version.
        parts = self.namespace.lower().strip().split(":")
        base_image = parts[0]
        version = parts[1] if len(parts) > 1 else "latest"

        # Generate Dockerfile content using the language config.
        repo_dir = f"{self.root_path}/input/repo/{self.full_name}"
        is_maven = os.path.exists(os.path.join(repo_dir, "pom.xml"))
        is_gradle = os.path.exists(os.path.join(repo_dir, "build.gradle"))

        dockerfile_content = self.language_config.get_dockerfile_content(
            base_image, version, is_maven=is_maven, is_gradle=is_gradle
        )

        with open(dockerfile_path, "w") as f:
            f.write(dockerfile_content)
        return f"{self.root_path}/input/repo/{self.full_name}"

    def commit_container(self):
        try:
            delete_dangling_image()
            image = self.container.commit(
                repository=f"{self.get_standard_container_name()}", tag="tmp"
            )
            return True
        except ContainerError as e:
            print(f"Error committing container: {e}")
            return None

    def generate_final_dockerfile(self):
        """Generate a Dockerfile containing all executed commands."""
        try:
            output_dir = f"{self.root_path}/output/{self.full_name}"
            os.makedirs(output_dir, exist_ok=True)

            # Generate Dockerfile content.
            dockerfile_lines = [f"FROM {self.namespace.replace('build_env_', '')}"]

            # Add initial configuration.
            dockerfile_lines.extend(
                [
                    "",
                    "# Configure pip",
                    "RUN mkdir -p ~/.pip && touch ~/.pip/pip.conf",
                    'RUN echo "[global]" >> ~/.pip/pip.conf && echo "[install]" >> ~/.pip/pip.conf',
                ]
            )

            # Add dependencies based on Python version.
            if (
                self.namespace.lower().strip().split(":")[0].replace("build_env_", "")
                == "python"
            ):
                python_version = (
                    self.namespace.lower().strip().split(":")[1].split("-")[0].strip()
                )
                if compare_versions(python_version, "3.8") >= 0:
                    dockerfile_lines.extend(
                        [
                            "",
                            "# Install system dependencies",
                            "RUN apt-get update && apt-get install -y curl",
                            "",
                            "# Install Poetry",
                            "RUN curl -sSL https://install.python-poetry.org | python -",
                            'ENV PATH="/root/.local/bin:$PATH"',
                            "",
                            "# Install base tools",
                            "RUN pip install pytest",
                            "RUN pip install openai -i https://mirrors.aliyun.com/pypi/simple",
                            "RUN pip install pipdeptree",
                            "",
                            "# Git config",
                            "RUN git config --global --add safe.directory /repo",
                        ]
                    )
                else:
                    dockerfile_lines.extend(
                        [
                            "",
                            "# Install system dependencies",
                            "RUN apt-get update && apt-get install -y curl",
                            "",
                            "# Install base tools",
                            "RUN pip install pytest",
                            "RUN pip install pipdeptree",
                            "",
                            "# Git config",
                            "RUN git config --global --add safe.directory /repo",
                        ]
                    )

            # Add working directory.
            dockerfile_lines.extend(
                [
                    "",
                    "# Set working directory",
                    "WORKDIR /repo",
                ]
            )
            # Extract installation commands from history.
            dockerfile_lines.append("")
            dockerfile_lines.append(
                "# Executed setup commands (generated from history)"
            )
            for cmd_info in self.commands:
                cmd = cmd_info.get("command", "")
                returncode = cmd_info.get("returncode", -1)

                # Keep only successful commands, and filter out commands unsuitable for a Dockerfile.
                if returncode == 0 and cmd.strip():
                    # Filter out unsuitable commands.
                    skip_patterns = [
                        "cd ",
                        "pwd",
                        "ls ",
                        "cat ",
                        "echo $",
                        "sleep",
                        "pytest",
                        "python -m pytest",
                    ]
                    should_skip = any(
                        cmd.strip().startswith(pattern) for pattern in skip_patterns
                    )

                    if not should_skip:
                        # For pip install, apt-get, etc., add to the Dockerfile.
                        patterns = [
                            "pip install",
                            "apt-get install",
                            "poetry install",
                            "npm install",
                        ]
                        # If using uv, include uv-related command patterns.
                        if self.use_uv:
                            patterns.extend(
                                [
                                    "uv pip install",
                                    "uv sync",
                                    "uv add",
                                    "uv pip sync",
                                ]
                            )

                        if any(pattern in cmd for pattern in patterns):
                            dockerfile_lines.append(f"RUN {cmd}")

            # Write Dockerfile.
            dockerfile_path = os.path.join(output_dir, "Dockerfile")
            with open(dockerfile_path, "w", encoding="utf-8") as f:
                f.write("\n".join(dockerfile_lines))

            # Copy test files and related config files.
            repo_path = f"{self.root_path}/input/repo/{self.full_name}"
            if os.path.exists(repo_path):
                # Copy the entire repo directory into output.
                import shutil

                dest_repo_path = os.path.join(output_dir, "repo")
                if os.path.exists(dest_repo_path):
                    shutil.rmtree(dest_repo_path)
                shutil.copytree(repo_path, dest_repo_path)

            # Generate usage documentation.
            readme_path = os.path.join(output_dir, "README.md")
            with open(readme_path, "w", encoding="utf-8") as f:
                f.write(f"""# {self.full_name} - Environment Setup

## Build Image

```bash
docker build -t {self.get_standard_container_name()}:final .
```

## Run Container

```bash
docker run -it --rm -v $(pwd)/repo:/repo {self.get_standard_container_name()}:final /bin/bash
```

## Command History

Below are the commands executed while setting up the environment:

""")
                for i, cmd_info in enumerate(self.commands, 1):
                    cmd = cmd_info.get("command", "")
                    returncode = cmd_info.get("returncode", -1)
                    status = "✅" if returncode == 0 else "❌"
                    f.write(f"{i}. {status} `{cmd}`\n")

            print(f"📝 Generated Dockerfile with {len(self.commands)} commands")
            return True

        except Exception as e:
            print(f"❌ Error generating Dockerfile: {e}")
            return False

    def save_as_image(self):
        """Commit the container as the final image."""
        try:
            delete_dangling_image()

            # Commit the container as the final image.
            image_name = f"{self.get_standard_container_name()}"
            image = self.container.commit(repository=image_name, tag="final")

            # Generate usage documentation.
            output_dir = f"{self.root_path}/output/{self.full_name}"
            os.makedirs(output_dir, exist_ok=True)

            readme_path = os.path.join(output_dir, "IMAGE_USAGE.md")
            with open(readme_path, "w", encoding="utf-8") as f:
                f.write(f"""# {self.full_name} - Image Usage Guide

## Image Info

- Image name: `{image_name}:final`
- Base image: `{self.namespace.replace("build_env_", "")}`

## Run Container

```bash
docker run -it --rm {image_name}:final /bin/bash
```

## Export Image

To share or back up the image:

```bash
# Export to a tar file
docker save {image_name}:final -o {self.get_standard_container_name()}_final.tar

# Import on another machine
docker load -i {self.get_standard_container_name()}_final.tar
```

## List Images

```bash
docker images | grep {image_name}
```

## Remove Image

```bash
docker rmi {image_name}:final
```

## Command History

Below are the commands executed while setting up the environment:

""")
                for i, cmd_info in enumerate(self.commands, 1):
                    cmd = cmd_info.get("command", "")
                    returncode = cmd_info.get("returncode", -1)
                    status = "✅" if returncode == 0 else "❌"
                    f.write(f"{i}. {status} `{cmd}`\n")

            print(f"🐳 Image saved as: {image_name}:final")
            print(f"📝 Usage guide saved to: {readme_path}")
            return True

        except Exception as e:
            print(f"❌ Error saving image: {e}")
            return False

    def build_image(self):
        """
        Build the Docker image.

        If use_repo_dockerfile=True and the repository contains a Dockerfile, use
        the repository Dockerfile; otherwise use the system-generated Dockerfile.

        Returns:
            tuple: (success: bool, used_repo_dockerfile: bool)
                   - success: whether the build succeeded
                   - used_repo_dockerfile: whether the repo Dockerfile was used
        """
        # Check whether to use the repo-provided Dockerfile.
        if (
            self.use_repo_dockerfile
            and self.repo_dockerfile_path
            and os.path.exists(self.repo_dockerfile_path)
        ):
            print(
                f"🐳 Using repo Dockerfile: {os.path.relpath(self.repo_dockerfile_path, self.root_path)}"
            )

            # Determine build context (directory containing the Dockerfile).
            build_context = os.path.dirname(self.repo_dockerfile_path)
            dockerfile_name = os.path.basename(self.repo_dockerfile_path)

            # Use the repo name as the image tag.
            image_tag = f"repo_{self.get_standard_container_name()}"
            self.namespace = image_tag

            print(f"📋 Build context: {build_context}")
            print(f"📋 Dockerfile: {dockerfile_name}")

            try:
                print(f"📋 Building image: {self.namespace}")

                # Build command.
                if dockerfile_name == "Dockerfile":
                    # Standard Dockerfile.
                    cmd = ["docker", "build", ".", "-t", self.namespace]
                else:
                    # Non-standard Dockerfile name (e.g. proxy.Dockerfile).
                    cmd = [
                        "docker",
                        "build",
                        ".",
                        "-f",
                        dockerfile_name,
                        "-t",
                        self.namespace,
                    ]

                subprocess.run(
                    cmd,
                    cwd=build_context,
                    check=True,
                )
                print(f"✅ Image built successfully: {self.namespace}")
                return True, True
            except subprocess.CalledProcessError as e:
                print(f"❌ Repo Dockerfile build failed: {e}")
                print("⚠️  Falling back to the system-generated Dockerfile")
                # Fallback marker: no longer use the repo Dockerfile.
                self.use_repo_dockerfile = False
                self.repo_dockerfile_path = None
                # Continue and try the system-generated Dockerfile.

        # Use the system-generated Dockerfile.
        if self.use_repo_dockerfile:
            print(
                "⚠️  Dockerfile not found in repo; using the system-generated Dockerfile"
            )
        print("🐳 Using system-generated Dockerfile")

        # Preserve original namespace for fallback.
        original_namespace = self.namespace
        build_context = self.create_dockerfile()
        dockerfile_name = "Dockerfile"
        self.namespace = "build_env_" + self.namespace

        try:
            print(f"📋 Building image: {self.namespace}")

            # Build command.
            cmd = ["docker", "build", ".", "-t", self.namespace]

            subprocess.run(
                cmd,
                cwd=build_context,
                check=True,
            )
            print(f"✅ Image built successfully: {self.namespace}")
            return True, False
        except subprocess.CalledProcessError as e:
            print(f"❌ Image build failed: {e}")
            print(
                f"⚠️  The recommended base image '{original_namespace}' failed to build"
            )

            # Try falling back to the default image.
            from libkit.command import get_default_namespace

            default_namespace = get_default_namespace(self.language)

            if original_namespace != default_namespace:
                print(f"🔄 Trying default base image: {default_namespace}")
                self.namespace = default_namespace

                # Regenerate Dockerfile.
                build_context = self.create_dockerfile()
                self.namespace = "build_env_" + self.namespace

                try:
                    print(f"📋 Building image: {self.namespace}")
                    cmd = ["docker", "build", ".", "-t", self.namespace]
                    subprocess.run(
                        cmd,
                        cwd=build_context,
                        check=True,
                    )
                    print(f"✅ Built successfully with default image: {self.namespace}")
                    return True, False
                except subprocess.CalledProcessError as fallback_error:
                    print(f"❌ Default image build also failed: {fallback_error}")
                    return False, False
            else:
                print("❌ Already using the default image; cannot fall back further")
                return False, False

    def _cleanup_existing_container(self, container_name):
        """Clean up any existing container with the same name."""
        try:
            # Check for an existing container with the same name.
            existing_container = None
            for container in self.client.containers.list(all=True):
                if container.name == container_name:
                    existing_container = container
                    break

            if existing_container:
                print(
                    f"⚠️ Found existing container with same name: {container_name} ({existing_container.short_id})"
                )
                if existing_container.status == "running":
                    print("🛑 Stopping running container...")
                    existing_container.stop()
                print("🗑️ Removing container...")
                existing_container.remove()
                print("✅ Cleaned up container with same name")
                return True
        except Exception as e:
            print(f"⚠️ Error cleaning up container with same name: {e}")
        return False

    def create_container(self, base_image=False):
        """
        Initialize a container.

        Returns:
            bool: whether the repo Dockerfile was used (for prompt selection)
        """
        print("🔍 Starting container creation")
        used_repo_dockerfile = False
        if not base_image:
            success, used_repo_dockerfile = self.build_image()
            if not success:
                raise Exception("Build image error!")
        image = f"{self.namespace}"
        host_path = "/tmp/patch"
        container_path = "/tmp/patch"

        # Clean up any existing container with the same name to avoid conflicts.
        self._cleanup_existing_container(self.container_name)

        try:
            # Configure environment variables to use mirror endpoints.
            environment = {
                # HuggingFace mirror configuration
                "HF_ENDPOINT": "https://hf-mirror.com",
                "HUGGINGFACE_HUB_CACHE": "/root/.cache/huggingface",
                # ModelScope mirror configuration
                "MODELSCOPE_CACHE": "/root/.cache/modelscope",
            }

            self.container = self.client.containers.run(
                image,
                command="/bin/bash",
                name=self.container_name,
                detach=True,
                tty=True,
                stdin_open=True,
                privileged=True,
                volumes={host_path: {"bind": container_path, "mode": "rw"}},
                environment=environment,
            )
            print(
                f"Container {self.container.name} {self.container.short_id} started with image {image}"
            )
            current_file_path = os.path.abspath(__file__)
            current_directory = os.path.dirname(current_file_path)
            project_directory = os.path.dirname(current_directory)
            cmd = f"chmod -R 777 {project_directory}/libkit/tools && docker cp {project_directory}/libkit/tools {self.container.name}:/home"
            print("📋 Running command:", cmd)
            subprocess.run(cmd, check=True, shell=True)
            cmd = f"docker cp {self.root_path}/input/repo/{self.full_name}/. {self.container.name}:/repo"
            print("📋 Running command:", cmd)
            subprocess.run(cmd, check=True, shell=True)
            return used_repo_dockerfile
        except Exception as e:
            print(f"Container start faild: {e}")
            return False

    def stop_container(self):
        if self.container:
            # 1. Clean up the shell first (use try/except to keep going on failure).
            if self.shell:
                try:
                    if self.shell.isalive():
                        self.shell.close(force=True)
                except Exception as e:
                    print(
                        f"⚠️  Error closing shell (will continue container cleanup): {e}"
                    )
                finally:
                    self.shell = None

            # 2. Save state based on save_mode.
            try:
                if self.save_mode == "dockerfile":
                    self.generate_final_dockerfile()
                    print(
                        f"✅ Dockerfile and test files saved to: {self.root_path}/output/{self.full_name}/"
                    )
                elif self.save_mode == "image":
                    self.save_as_image()
                    print(
                        f"✅ Container saved as image: {self.get_standard_container_name()}:final"
                    )
            except Exception as e:
                print(f"⚠️  Error saving container state (will continue cleanup): {e}")

            # 3. Stop and remove the container (use try/except for cleanup).
            try:
                self.container.stop()
                self.container.remove()
                print(f"Container {self.container.short_id} stopped and removed")
            except Exception as e:
                print(f"⚠️  Error stopping/removing container: {e}")
                # Try force remove.
                try:
                    self.container.remove(force=True)
                    print(f"Container {self.container.short_id} force removed")
                except Exception as e2:
                    print(f"❌ Force remove also failed: {e2}")
            finally:
                self.container = None

            # 4. Clean up temporary images.
            try:
                if self.save_mode == "none":
                    # Use DEVNULL instead of PIPE to avoid file descriptor leaks.
                    subprocess.run(
                        f"docker rmi {self.get_standard_container_name()}:tmp",
                        shell=True,
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL,
                    )
                elif self.save_mode != "image":
                    # Also delete temporary images in dockerfile mode.
                    subprocess.run(
                        f"docker rmi {self.get_standard_container_name()}:tmp",
                        shell=True,
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL,
                    )
            except Exception as e:
                print(f"⚠️  Error cleaning temporary image (can be ignored): {e}")

            # 5. Close the Docker client to release file descriptors.
            try:
                if self.client:
                    self.client.close()
                    self.client = None
            except Exception as e:
                print(f"⚠️  Error closing Docker client (can be ignored): {e}")

        return self.commands

    def get_session(self):
        self.create_shell()

        class Session:
            def __init__(self, env):
                self.env = env

            def __enter__(self):
                """Context manager entry."""
                return self

            def __exit__(self, exc_type, exc_val, exc_tb):
                """Context manager exit - ensures session cleanup."""
                try:
                    self.close()
                except Exception as e:
                    print(f"⚠️  Error during Session context cleanup: {e}")
                # Do not suppress exceptions; let them propagate.
                return False

            def get_returncode(self):
                echo_returncode = """echo $?"""
                self.env.shell.sendline(echo_returncode)
                self.env.shell.expect([r"root@.*:.*# "], timeout=600)
                # Get output before the matched prompt from shell.before.
                output = self.env.shell.before.decode("utf-8").strip()
                output = output.replace("\x1b[?2004l\r", "")

                # Parse output lines, excluding the echoed command and the final prompt.
                output_lines1 = output.split("\r\n")

                if len(output_lines1) > 1:
                    last_line = output_lines1[-1]
                    output_lines1 = output_lines1[1:-1]
                    id = last_line.find("""\x1b[""")
                    if id != -1 and len(last_line[:id].strip()) > 0:
                        output_lines1.append(last_line[:id].strip())
                return_code = "\n".join(output_lines1).strip()
                return int(return_code)

            def is_shell_alive(self) -> bool:
                """
                Quickly check whether the shell responds, to decide whether recovery is needed.

                Returns:
                    True if the shell responds normally; False on timeout or error.
                """
                try:
                    # Send an empty command to probe shell responsiveness.
                    self.env.shell.sendline("")
                    self.env.shell.expect([r"root@.*:.*# ", r"[$#]"], timeout=2)
                    return True
                except pexpect.TIMEOUT:
                    return False
                except Exception:
                    return False

            def try_recover_shell(self):
                """
                Try to recover a stuck shell.

                Send Ctrl+C to interrupt a potentially hanging command.

                Returns:
                    True if recovery succeeds; False otherwise.
                """
                try:
                    # Send Ctrl+C (ASCII 3) to interrupt the current command.
                    self.env.shell.send("\x03")
                    # Wait briefly to see whether it recovers.
                    self.env.shell.expect([r"root@.*:.*# ", r"[$#]", r"\^C"], timeout=2)
                    # Re-check liveness.
                    return self.is_shell_alive()
                except:
                    return False

            # A special helper used by download.
            def execute_simple(self, command, timeout=300):
                self.env.commit_container()
                if command[-1] != "&":
                    start_time = time.time()
                    self.env.commands.append(
                        {"command": command, "returncode": -2, "time": -1, "dir": "/"}
                    )
                    self.env.shell.sendline(command + " && sleep 0.5")
                    self.env.commands[-1]["returncode"] = -1
                else:
                    start_time = time.time()
                    self.env.commands.append(
                        {"command": command, "returncode": -2, "time": -1, "dir": "/"}
                    )
                    self.env.shell.sendline(command)
                    self.env.commands[-1]["returncode"] = -1

                self.env.shell.expect(
                    [r"root@.*:.*# "], timeout=600
                )  # Wait for bash prompt with timeout.
                end_time = time.time()
                elasped_time = end_time - start_time
                self.env.commands[-1]["time"] = elasped_time

                # Get output before the matched prompt from shell.before.
                output = self.env.shell.before.decode("utf-8").strip()
                output = output.replace("\x1b[?2004l\r", "")

                # Parse output lines, excluding the echoed command and the final prompt.
                output_lines = output.split("\r\n")

                if len(output_lines) > 1:
                    last_line = output_lines[-1]
                    output_lines = output_lines[1:-1]
                    id = last_line.find("""\x1b[""")
                    if id != -1 and len(last_line[:id].strip()) > 0:
                        output_lines.append(last_line[:id].strip())
                res = "\n".join(output_lines).strip()
                if len(res.split(" ")) > 5000:
                    res = "The output is too long, so we've truncated it to show you the first and last 2500 words."
                    res += (
                        " ".join(res.split(" ")[:2500])
                        + "\n"
                        + " ".join(res.splitlines()[-2500:])
                    )
                return_code = self.get_returncode()
                self.env.commands[-1]["returncode"] = return_code
                if str(return_code) == "0":
                    return True, res
                else:
                    self.env.switch_to_pre_image()
                    return False, res

            def execute(self, command, timeout=300):
                try:
                    if "hatch shell" == command.lower().strip():
                        return (
                            "You are not allowed to use commands like `hatch shell` that would open a new shell!!!",
                            -1,
                        )
                    # Execute command in the persistent shell.
                    if "$pwd$" == command.lower().strip():
                        # Degrade gracefully: return default values if pwd fails.
                        try:
                            # Ensure the shell is ready by waiting for a prompt.
                            try:
                                self.env.shell.expect(
                                    [r"root@.*:.*# ", r"[$#]"], timeout=1
                                )
                            except:
                                pass  # Might already be at the prompt.

                            command = "pwd"
                            self.env.shell.sendline(command)
                            # Reduce timeout from 600 seconds to 5 seconds.
                            self.env.shell.expect(
                                [r"root@.*:.*# "], timeout=5
                            )  # Fail fast to avoid long waits.

                            # Get output before the matched prompt from shell.before.
                            output = self.env.shell.before.decode("utf-8").strip()
                            output = output.replace("\x1b[?2004l\r", "")

                            # Parse output lines, excluding the echoed command and the final prompt.
                            output_lines = output.split("\r\n")

                            if len(output_lines) > 1:
                                last_line = output_lines[-1]
                                output_lines = output_lines[1:-1]
                                id = last_line.find("""\x1b[""")
                                if id != -1 and len(last_line[:id].strip()) > 0:
                                    output_lines.append(last_line[:id].strip())

                            # Return the first non-empty line as the directory.
                            for line in output_lines:
                                if line.strip():
                                    return line.strip(), 0
                            return "/repo", 0  # Default to /repo.

                        except pexpect.TIMEOUT:
                            # If pwd times out, return a default to avoid blocking subsequent commands.
                            # Use cached dir if available; otherwise return /repo.
                            if (
                                hasattr(self.env, "_cached_dir")
                                and self.env._cached_dir
                            ):
                                return self.env._cached_dir, 0
                            return "/repo", 0

                    if command.split(" ")[0] == "rm" and (
                        command.split("/")[-1].startswith("test_")
                        or command.split("/")[-1].endswith("_test.py")
                    ):
                        msg = "Please do not directly delete the testing file to pass the test!"
                        result_message = msg
                        return result_message, 1
                    elif command.split(" ")[0] == "mv" and (
                        command.split("/")[-1].startswith("test_")
                        or command.split("/")[-1].endswith("_test.py")
                    ):
                        msg = "Please do not directly move the testing file to pass the test!"
                        result_message = msg
                        return result_message, 1
                    else:
                        if command[-1] != "&":
                            # if not (command.split()[0].strip() in SAFE_CMD and '>' not in command):
                            #     self.env.commit_container()
                            start_time = time.time()
                            # If pwd fails, use cached/default values.
                            try:
                                dir, return_code = self.execute("$pwd$")
                                # Cache the directory when successfully retrieved.
                                if return_code == 0:
                                    self.env._cached_dir = dir
                            except Exception as e:
                                # pwd failed; use cache or default.
                                dir = getattr(self.env, "_cached_dir", "/repo")
                            self.env.commands.append(
                                {
                                    "command": command,
                                    "returncode": -2,
                                    "time": -1,
                                    "dir": dir,
                                }
                            )
                            self.env.shell.sendline(command + " && sleep 0.5")
                            self.env.commands[-1]["returncode"] = -1
                        else:
                            # if not (command.split()[0].strip() in SAFE_CMD and '>' not in command):
                            #     self.env.commit_container()
                            start_time = time.time()
                            # If pwd fails, use cached/default values.
                            try:
                                dir, return_code = self.execute("$pwd$")
                                # Cache the directory when successfully retrieved.
                                if return_code == 0:
                                    self.env._cached_dir = dir
                            except Exception as e:
                                # pwd failed; use cache or default.
                                dir = getattr(self.env, "_cached_dir", "/repo")
                            self.env.commands.append(
                                {
                                    "command": command,
                                    "returncode": -2,
                                    "time": -1,
                                    "dir": dir,
                                }
                            )
                            self.env.shell.sendline(command)
                            self.env.commands[-1]["returncode"] = -1

                        self.env.shell.expect(
                            [r"root@.*:.*# "], timeout=timeout * 2
                        )  # Wait for bash prompt with timeout.
                        end_time = time.time()
                        elasped_time = end_time - start_time
                        self.env.commands[-1]["time"] = elasped_time

                        # Get output before the matched prompt from shell.before.
                        output = self.env.shell.before.decode("utf-8").strip()
                        output = output.replace("\x1b[?2004l\r", "")
                        # Parse output lines, excluding the echoed command and the final prompt.
                        output_lines = output.split("\r\n")

                        if len(output_lines) > 1:
                            last_line = output_lines[-1]
                            output_lines = output_lines[1:-1]
                            id = last_line.find("""\x1b[""")
                            if id != -1 and len(last_line[:id].strip()) > 0:
                                output_lines.append(last_line[:id].strip())
                        try:
                            return_code = self.get_returncode()
                        except:
                            return_code = 123
                        try:
                            self.env.commands[-1]["returncode"] = return_code
                        except:
                            self.env.commands[-1]["returncode"] = 111
                            self.env.commands[-1]["error_msg"] = return_code
                        result_message = "\n".join(output_lines)
                        if (
                            "Congratulations, you have successfully configured the environment!"
                            in result_message
                            or command == "python /home/tools/generate_diff.py"
                            or command == "pipdeptree --json-tree"
                            or command == "pipdeptree"
                        ):
                            return result_message, return_code
                        else:
                            result_message = (
                                f"Running `{command}`...\n" + result_message + "\n"
                            )
                            return truncate_msg(result_message, command), return_code
                except pexpect.TIMEOUT:
                    # if match_runtest(command) or match_poetryruntest(command):
                    #     os.system(
                    #         f"touch {self.env.root_path}/output/{self.env.full_name}/TIMEOUT"
                    #     )
                    #     sys.exit(123)

                    # After timeout, attempt to recover the shell.
                    shell_recovered = False
                    if not self.is_shell_alive():
                        # Shell not responding; try Ctrl+C.
                        shell_recovered = self.try_recover_shell()

                    # Shell recreation: if Ctrl+C fails, recreate the Shell.
                    if not shell_recovered:
                        print("⚠️  Ctrl+C recovery failed; trying to recreate Shell...")
                        if self.env.recreate_shell(target_dir="/repo"):
                            shell_recovered = True
                            print("✓ Shell recreated successfully; switched to /repo")
                        else:
                            print("❌ Shell recreation failed")

                    partial_output = self.env.shell.before.decode("utf-8").strip()
                    partial_output_lines = partial_output.split("\n")
                    if len(partial_output_lines) > 1:
                        partial_output_lines = partial_output_lines[1:-1]
                    partial_output = "\n".join(partial_output_lines)

                    # Provide more detailed timeout info and suggestions.
                    timeout_msg = f"Error: Command '{command}' timed out after {timeout} seconds.\n"
                    if shell_recovered:
                        timeout_msg += "✓ Shell recovered/recreated; you can continue with subsequent commands.\n"
                    else:
                        timeout_msg += "❌ Shell recovery and recreation both failed; subsequent commands will fail.\n"
                    timeout_msg += "⏱️  Suggestions:\n"
                    timeout_msg += "  1. Check whether the command is stuck downloading or waiting for input\n"
                    timeout_msg += "  2. If this is dependency installation, consider using a mirror\n"
                    timeout_msg += "  3. Consider installing dependencies in batches or increasing the timeout\n"
                    timeout_msg += "  4. Check the README for any special installation instructions\n"
                    timeout_msg += f"\nPartial output:\n{partial_output}"

                    return (timeout_msg, 1)

            def edit(
                self,
                edit_tmp_file: str,
                project_path: str,
                file_path=None,
                start_line=0,
                end_line=0,
                timeout=600,
            ):
                if file_path:
                    if file_path.split("/")[-1].startswith("test_") or file_path("/")[
                        -1
                    ].endswith("_test.py"):
                        msg = (
                            "Running Edit...\n"
                            + f"You are trying to modify file {file_path}, but we require that you should not modify the testing files. Please consider alternative solutions."
                            + "\n"
                        )
                        return msg, 1
                if not file_path:
                    command = f"python /home/tools/code_edit.py -t '{edit_tmp_file}' -p '{project_path}'"
                else:
                    command = f"python /home/tools/code_edit.py -t '{edit_tmp_file}' -p '{project_path}' -f '{file_path}' -s {start_line} -e {end_line}"
                try:
                    start_time = time.time()
                    self.env.commands.append(
                        {"command": command, "returncode": -2, "time": -1, "dir": "/"}
                    )
                    # Execute command in the persistent shell.
                    self.env.shell.sendline(command)
                    end_time = time.time()
                    self.env.commands[-1]["returncode"] = -1
                    elasped_time = end_time - start_time
                    self.env.commands[-1]["time"] = elasped_time
                    self.env.shell.expect(
                        [r"root@.*:.*# "], timeout=timeout
                    )  # Wait for bash prompt with timeout.

                    # Get output before the matched prompt from shell.before.
                    output = self.env.shell.before.decode("utf-8").strip()

                    # Parse output lines, excluding the echoed command and the final prompt.
                    output_lines = output.split("\r\n")
                    if len(output_lines) > 1:
                        output_lines = output_lines[
                            1:-1
                        ]  # Exclude the echoed command line.

                    result_message = "Running Edit...\n" + "\n".join(output_lines)
                    try:
                        return_code = self.get_returncode()
                    except:
                        return_code = 123
                    self.env.commands[-1]["returncode"] = return_code
                    return result_message, return_code

                except pexpect.TIMEOUT:
                    return (
                        "Running Edit...\n"
                        + f"Error: Edit timed out after {timeout} seconds."
                        + "\n",
                        1,
                    )

            def close(self):
                """Close the session and clean up the shell."""
                if self.env.shell:
                    try:
                        self.env.shell.sendline("exit")
                        self.env.shell.expect(pexpect.EOF, timeout=5)
                    except Exception as e:
                        print(f"⚠️  Failed to send exit (will force close): {e}")

                    try:
                        self.env.shell.close(force=True)
                    except Exception as e:
                        print(f"⚠️  Failed to close shell: {e}")
                    finally:
                        self.env.shell = None  # Always set to None.

        return Session(self)

    def change_python_version(self, python_version):
        try:
            self.commit_container()
        except Exception as e:
            print(
                f"⚠️ Failed to commit container; continuing to change Python version: {e}"
            )
        self.namespace = f"python:{python_version}"

        # Create a new container.
        result = self.create_container()
        if result == -1:
            # Container creation failed; attempt rollback.
            print("❌ New container creation failed; attempting rollback...")
            if hasattr(self, "switch_to_pre_image"):
                rollback_success = self.switch_to_pre_image()
                if rollback_success:
                    return "❌ Failed to change Python version. Rolled back to the previous state. Try another Python version."
                else:
                    return "❌ Failed to change Python version, and rollback also failed. The container may be in an inconsistent state."
            else:
                return "❌ Failed to change Python version. Cannot roll back to the previous state."

        # Container created successfully.
        print(f"✅ Python version changed successfully to {python_version}")
        return self

    def change_java_version(self, java_version):
        """
        Switch Java version.

        Args:
            java_version: Java version, e.g. "11", "17", "21".

        Returns:
            self, or an error message string.
        """
        try:
            self.commit_container()
        except Exception as e:
            print(
                f"⚠️ Failed to commit container; continuing to change Java version: {e}"
            )

        # Use eclipse-temurin as the base image.
        self.namespace = f"eclipse-temurin:{java_version}"

        # Create a new container.
        result = self.create_container()
        if result == -1:
            # Container creation failed; attempt rollback.
            print("❌ New container creation failed; attempting rollback...")
            if hasattr(self, "switch_to_pre_image"):
                rollback_success = self.switch_to_pre_image()
                if rollback_success:
                    return "❌ Failed to change Java version. Rolled back to the previous state. Try another Java version."
                else:
                    return "❌ Failed to change Java version, and rollback also failed. The container may be in an inconsistent state."
            else:
                return "❌ Failed to change Java version. Cannot roll back to the previous state."

        # Container created successfully.
        print(f"✅ Java version changed successfully to {java_version}")
        return self

    def change_node_version(self, node_version):
        """
        Switch Node.js version.

        Args:
            node_version: Node.js version, e.g. "18", "20", "22".

        Returns:
            self, or an error message string.
        """
        try:
            self.commit_container()
        except Exception as e:
            print(
                f"⚠️ Failed to commit container; continuing to change Node.js version: {e}"
            )

        # Use node as the base image.
        self.namespace = f"node:{node_version}"

        # Create a new container.
        result = self.create_container()
        if result == -1:
            # Container creation failed; attempt rollback.
            print("❌ New container creation failed; attempting rollback...")
            if hasattr(self, "switch_to_pre_image"):
                rollback_success = self.switch_to_pre_image()
                if rollback_success:
                    return "❌ Failed to change Node.js version. Rolled back to the previous state. Try another Node.js version."
                else:
                    return "❌ Failed to change Node.js version, and rollback also failed. The container may be in an inconsistent state."
            else:
                return "❌ Failed to change Node.js version. Cannot roll back to the previous state."

        # Container created successfully.
        print(f"✅ Node.js version changed successfully to {node_version}")
        return self

    def change_rust_version(self, rust_version):
        """
        Switch Rust version.

        Args:
            rust_version: Rust version, e.g. "1.70", "1.75", "latest".

        Returns:
            self, or an error message string.
        """
        try:
            self.commit_container()
        except Exception as e:
            print(
                f"⚠️ Failed to commit container; continuing to change Rust version: {e}"
            )

        # Use rust as the base image.
        self.namespace = f"rust:{rust_version}"

        # Create a new container.
        result = self.create_container()
        if result == -1:
            # Container creation failed; attempt rollback.
            print("❌ New container creation failed; attempting rollback...")
            if hasattr(self, "switch_to_pre_image"):
                rollback_success = self.switch_to_pre_image()
                if rollback_success:
                    return "❌ Failed to change Rust version. Rolled back to the previous state. Try another Rust version."
                else:
                    return "❌ Failed to change Rust version, and rollback also failed. The container may be in an inconsistent state."
            else:
                return "❌ Failed to change Rust version. Cannot roll back to the previous state."

        # Container created successfully.
        print(f"✅ Rust version changed successfully to {rust_version}")
        return self

    def switch_to_pre_image(self):
        """Switch to the previously committed temporary image (for rollback)."""
        try:
            # Use the same image name as commit_container.
            tmp_image_name = f"{self.get_standard_container_name()}:tmp"
            print(f"🔄 Switching to temporary image: {tmp_image_name}")

            # Clean up any containers with the same name (including the current one).
            self._cleanup_existing_container(self.container_name)
            # Ensure self.container is None to avoid follow-up errors.
            self.container = None
            self.shell = None

            host_path = "/tmp/patch"
            container_path = "/tmp/patch"

            # Configure environment variables to use mirror endpoints.
            environment = {
                # HuggingFace mirror configuration
                "HF_ENDPOINT": "https://hf-mirror.com",
                "HUGGINGFACE_HUB_CACHE": "/root/.cache/huggingface",
                # ModelScope mirror configuration
                "MODELSCOPE_CACHE": "/root/.cache/modelscope",
            }

            # Create and start a new container using the tmp image.
            self.container = self.client.containers.run(
                tmp_image_name,
                detach=True,
                tty=True,
                stdin_open=True,
                volumes={host_path: {"bind": container_path, "mode": "rw"}},
                privileged=True,
                name=self.container_name,
                environment=environment,
            )

            # Copy tools and repo files into the new container (same logic as create_container).
            current_file_path = os.path.abspath(__file__)
            current_directory = os.path.dirname(current_file_path)
            project_directory = os.path.dirname(current_directory)
            cmd = f"chmod -R 777 {project_directory}/libkit/tools && docker cp {project_directory}/libkit/tools {self.container.name}:/home"
            print("📋 Running command:", cmd)
            subprocess.run(cmd, check=True, shell=True)
            cmd = f"docker cp {self.root_path}/input/repo/{self.full_name} {self.container.name}:/repo"
            print("📋 Running command:", cmd)
            subprocess.run(cmd, check=True, shell=True)

            # Create a new shell session.
            self.shell = None  # Reset shell.
            self.create_shell()
            print("✅ Rolled back to temporary image successfully")
            return True

        except ImageNotFound as e:
            print(f"❌ Temporary image not found: {e}")
            return False
        except ContainerError as e:
            print(f"❌ Failed to switch container: {e}")
            return False
        except Exception as e:
            print(f"❌ Unexpected error during rollback: {e}")
            return False


#     # def change_base_image(self, base_image_name):
#     #     try:
#     #         self.commit_container()
#     #     except:
#     #         pass
#     #     self.namespace = base_image_name.strip().lower()
#     #     try:
#     #         self.start_container()
#     #     except Exception as e:
#     #         self.switch_to_pre_image()
#     #         return f'Change base image wrong! We have already rollback to the previous state. Please try another base image!\n{e}'
#     #     return self


#     def commit_container(self):
#         try:
#             delete_dangling_image()
#             # Commit the container to an image with a fixed name.
#             image = self.container.commit(repository=f"{self.full_name.lower().replace('/', '_').replace('-', '_')}", tag='tmp')
#             # subprocess.run(f'docker commit {self.container.name} running_env:tmp', shell=True)
#             # print(f"Container {self.container.name} committed as image running_env:tmp.")
#             return True
#         except docker.errors.ContainerError as e:
#             print(f"Error committing container: {e}")
#             return None

#     def switch_to_pre_image(self):
#         try:
#             # tmp_image_name = "running_env:tmp"
#             tmp_image_name = f"{self.full_name.lower().replace('/', '_').replace('-', '_')}:tmp"
#             # print(f"Switching to tmp image: {tmp_image_name}")

#             # Stop and remove the existing container.
#             if self.container:
#                 self.container.stop()
#                 self.container.remove()
#                 delete_dangling_image()

#             host_path = '/tmp/patch'
#             container_path = '/tmp/patch'
#             # Create and start a new container using the tmp image.
#             self.container = self.client.containers.run(
#                 tmp_image_name,
#                 detach=True,
#                 tty=True,
#                 stdin_open=True,
#                 volumes={host_path: {'bind': container_path, 'mode': 'rw'}},
#                 privileged=True,
#                 mem_limit='30g',
#                 network_mode='bridge',
#                 cpuset_cpus='0-7',
#                 )

#             # Start a new shell session.
#             self.start_shell()
#             return True

#         except docker.errors.ImageNotFound as e:
#             print(f"Image not found: {e}")
#             return False
#         except docker.errors.ContainerError as e:
#             print(f"Error switching to tmp container: {e}")
#             return False
#         except Exception as generic_error:
#             print(f"An unexpected error occurred: {generic_error}")
#             return False

#     # Get the project path inside the container.
#     def get_project_path(self):
#         project_path = self.container.exec_run("pwd").output.decode().strip()
#         return project_path

#     def stop_container(self):
#         if self.container:
#             if self.shell and self.shell.isalive():
#                 self.shell.close(force=True)  # Ensure the shell is closed.
#                 self.shell = None
#             self.container.stop()
#             self.container.remove()
#             print(f"Container {self.container.short_id} stopped and removed")
#             self.container = None
#             subprocess.run(f"docker rmi {self.full_name.lower().replace('/', '_').replace('-', '_')}:tmp > /dev/null 2>&1", shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
#         return self.commands


if __name__ == "__main__":
    print("<omitted>")
    # from conflict_list import ConflictList
    # from waiting_list import WaitingList
    # waiting_list = WaitingList()
    # conflict_list = ConflictList()
    # sandbox = Sandbox("python:3.10", "basf/MolPipeline")
    # sandbox.start_container()
    # session = sandbox.get_session()
    # while True:
    #     a = input()
    #     result, return_code = session.execute(a, waiting_list, conflict_list)
    #     print('result:\n' + result)
    #     print('return_code:\n' + str(return_code))
    # session.close()
    # sandbox.stop_container()
