"""Task 8 — end-to-end orchestrator (``build.py``).

``build_dep_graph`` wires the pipeline (scan -> map -> resolve -> seed -> install
-> probe -> certify) over a tiny fixture repo, driven entirely by a
``FakeExecutor`` (no Docker/network/uv).  The canned outputs below model a repo
that imports ``cv2`` (needs libGL.so.1), ``PIL`` (clean), and ``psycopg2`` (build
fails: pg_config missing), so the run exercises every node type:
Test / Import / Package / SystemLib / Tool.

Resolution is HOST-side and install/probe/certify are CONTAINER-side; the unit
test injects the SAME ``FakeExecutor`` for both (``host_executor=`` kwarg).

Native gaps here surface as fresh ``discovered_by=PROBE`` nodes (soname/tool-
name keyed): this fixture's closure is ``uv pip compile``-style text (no
``build_from_source`` signal), so all packages have unknown build mode (None).
``seed_wheel_oracle_prior`` (construction-enrichment cluster 1a) seeds
``tool:build-essential`` for these unknowns; specific ``-dev`` headers remain
undeclared and surface as fresh PROBE nodes (soname/tool-name keyed). See
``test_build_native_gaps_are_fresh_probe_nodes_without_a_prior`` for the
documented coverage tradeoff.
"""

from __future__ import annotations

from python_deps.depgraph.build import build_dep_graph
from python_deps.depgraph.executor import CommandResult
from python_deps.depgraph.ids import (
    TEST_NODE_ID,
    binary_id,
    import_id,
    package_id,
    syslib_id,
    tool_id,
)
from python_deps.depgraph.schema import DiscoveredBy, NodeType, State

CANNED_CLOSURE = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile - --python-version 3.11
numpy==1.26.4
    # via opencv-python
opencv-python==4.9.0.80
    # via -r -
Pillow==10.3.0
    # via -r -
psycopg2==2.9.9
    # via -r -
"""

INSTALL_STDERR = (
    "Building wheel for psycopg2 (setup.py): started\n"
    "    Error: pg_config executable not found.\n"
    "Building wheel for psycopg2 (setup.py): finished with status 'error'\n"
)


def _r(returncode=0, stdout="", stderr=""):
    return CommandResult(
        command="", returncode=returncode, stdout=stdout, stderr=stderr
    )


def _make_repo(tmp_path):
    (tmp_path / "app.py").write_text(
        "import os\nimport cv2\nfrom PIL import Image\nimport psycopg2\n"
    )
    # Roots are manifest-declared only (imports never generate roots), so the
    # deps this repo needs must be declared for the closure to resolve.
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname="fx"\nversion="0"\n'
        'dependencies=["opencv-python","Pillow","psycopg2"]\n'
    )
    return str(tmp_path)


def _make_executor():
    from conftest import FakeExecutor  # type: ignore

    return FakeExecutor(
        responses={
            "uv pip compile": _r(stdout=CANNED_CLOSURE),
            "pip install": _r(returncode=1, stderr=INSTALL_STDERR),
            # Stage 4a certified relink: the CONTAINER's packages_distributions()
            # is the SOLE Import->Package source now that the provisional Stage 3a
            # heuristic is retired. Honest post-install map: cv2/PIL/numpy are
            # installed and reported; psycopg2 FAILED to build (see INSTALL_STDERR)
            # so it is absent here -> its import is honestly flagged unresolved.
            "packages_distributions": _r(
                stdout='{"cv2": ["opencv-python"], "PIL": ["Pillow"], "numpy": ["numpy"]}'
            ),
            # import probes (also reused by certification of the import nodes)
            "import cv2": _r(
                returncode=1,
                stderr="ImportError: libGL.so.1: cannot open shared object file",
            ),
            "import PIL": _r(returncode=0),
            "import psycopg2": _r(
                returncode=1, stderr="ModuleNotFoundError: No module named 'psycopg2'"
            ),
            "import numpy": _r(returncode=0),
            # package certification
            "pip show opencv-python": _r(returncode=0),
            "pip show numpy": _r(returncode=0),
            "pip show Pillow": _r(returncode=0),
            "pip show psycopg2": _r(returncode=1, stderr="WARNING: Package(s) not found"),
            # system / toolchain certification
            "ldconfig": _r(returncode=1),
            "command -v pg_config": _r(returncode=1),
            # goal
            "pytest": _r(returncode=1, stderr="tests failed"),
        }
    )


def _build(tmp_path):
    ex = _make_executor()
    return build_dep_graph(_make_repo(tmp_path), ex, host_executor=ex)


def test_build_produces_all_node_types(tmp_path):
    graph = _build(tmp_path)

    # Test goal node.
    assert graph.get(TEST_NODE_ID) is not None
    # Imports (stdlib ``os`` excluded).
    for name in ("cv2", "PIL", "psycopg2"):
        assert graph.get(import_id(name)) is not None
    assert graph.get(import_id("os")) is None
    # Packages from the resolver.
    assert graph.get(package_id("opencv-python", "4.9.0.80")) is not None
    assert graph.get(package_id("numpy", "1.26.4")) is not None
    assert graph.get(package_id("Pillow", "10.3.0")) is not None
    assert graph.get(package_id("psycopg2", "2.9.9")) is not None
    # SystemLib + Tool — no RESOLVER prediction to reconcile into (no curated
    # table, no build_from_source signal in this fixture), so the observed
    # gaps surface as FRESH PROBE nodes, keyed by soname/tool name.
    assert graph.get(syslib_id("libGL.so.1")) is not None
    assert graph.get(binary_id("pg_config")) is not None
    assert graph.get(syslib_id("libgl1")) is None
    assert graph.get(tool_id("libpq-dev")) is None


def test_build_discovers_subprocess_cli_tools(tmp_path):
    """Finding C: an external tool the repo shells out to (adb) becomes a Tool
    node with an apt fix — even though it is neither a linked library (ldd) nor a
    pip build tool. Wired via Stage 3a'' (subprocess_scan)."""
    (tmp_path / "app.py").write_text(
        "import cv2\nimport subprocess\nsubprocess.run(['adb', 'devices'])\n"
    )
    ex = _make_executor()
    ex.responses["command -v adb"] = _r(returncode=1)  # absent on the slim base
    graph = build_dep_graph(str(tmp_path), ex, host_executor=ex)

    adb = graph.get(tool_id("adb"))
    assert adb is not None and adb.type is NodeType.TOOL
    assert adb.chosen_fix == "apt:adb"
    assert adb.discovered_by is DiscoveredBy.STATIC_SCAN
    assert adb.state is State.MISSING           # command -v adb -> rc1
    # hung off the Project anchor (the repo's own code invokes it)
    from python_deps.depgraph.ids import project_id
    assert any(e.dst == tool_id("adb") and e.src == project_id(tmp_path.name)
               for e in graph.edges)


def test_build_requires_topology(tmp_path):
    graph = _build(tmp_path)

    edges = {(e.src, e.dst) for e in graph.edges}
    # Test -> Imports
    assert (TEST_NODE_ID, import_id("cv2")) in edges
    assert (TEST_NODE_ID, import_id("psycopg2")) in edges
    # Import -> Package
    assert (import_id("cv2"), package_id("opencv-python", "4.9.0.80")) in edges
    assert (import_id("PIL"), package_id("Pillow", "10.3.0")) in edges
    # Package -> Package (transitive, from uv annotation)
    assert (
        package_id("opencv-python", "4.9.0.80"),
        package_id("numpy", "1.26.4"),
    ) in edges
    # Package -> SystemLib / Tool (fresh PROBE discovery, no prior to reconcile into)
    assert (
        package_id("opencv-python", "4.9.0.80"),
        syslib_id("libGL.so.1"),
    ) in edges
    assert (package_id("psycopg2", "2.9.9"), binary_id("pg_config")) in edges


def test_build_certified_states(tmp_path):
    graph = _build(tmp_path)

    assert graph.get(package_id("opencv-python", "4.9.0.80")).state is State.SATISFIED
    assert graph.get(package_id("numpy", "1.26.4")).state is State.SATISFIED
    assert graph.get(package_id("Pillow", "10.3.0")).state is State.SATISFIED
    assert graph.get(package_id("psycopg2", "2.9.9")).state is State.MISSING

    assert graph.get(import_id("PIL")).state is State.SATISFIED
    assert graph.get(import_id("cv2")).state is State.MISSING
    assert graph.get(import_id("psycopg2")).state is State.MISSING

    assert graph.get(syslib_id("libGL.so.1")).state is State.MISSING
    assert graph.get(binary_id("pg_config")).state is State.MISSING
    assert graph.get(TEST_NODE_ID).state is State.MISSING


def test_build_native_gaps_are_fresh_probe_nodes_without_a_prior(tmp_path):
    """No curated table and no build_from_source signal in this fixture ->
    seed_wheel_oracle_prior predicts only the generic build-essential toolchain,
    not specific ``-dev`` headers. The observed native gaps (libGL, libpq-dev)
    have no RESOLVER prediction and surface as fresh discovered_by=PROBE nodes
    (the design's documented coverage tradeoff — Risk #2 in the construction-
    enrichment design)."""
    graph = _build(tmp_path)

    libgl = graph.get(syslib_id("libGL.so.1"))
    pg_config = graph.get(binary_id("pg_config"))
    assert libgl.discovered_by is DiscoveredBy.PROBE
    assert pg_config.discovered_by is DiscoveredBy.PROBE
    assert libgl.check_command == "ldconfig -p | grep libGL.so.1"
    assert pg_config.check_command == "command -v pg_config"
    assert libgl.fix_candidates == ("apt:libgl1",)        # os_resolver.PROVIDER_TABLE still resolves it
    assert pg_config.fix_candidates == ("apt:libpq-dev",)  # os_resolver.PROVIDER_TABLE still resolves it
    assert any(a.outcome == "failed" for a in libgl.attempts)


def test_build_discovered_by_stamping(tmp_path):
    graph = _build(tmp_path)

    assert graph.get(import_id("cv2")).discovered_by is DiscoveredBy.STATIC_SCAN
    assert graph.get(TEST_NODE_ID).discovered_by is DiscoveredBy.GOAL
    assert (
        graph.get(package_id("numpy", "1.26.4")).discovered_by
        is DiscoveredBy.RESOLVER
    )


def test_build_discovered_cycle_per_stage(tmp_path):
    graph = _build(tmp_path)

    # stage 1 (scan): Test + Imports
    assert graph.get(TEST_NODE_ID).discovered_cycle == 1
    assert graph.get(import_id("cv2")).discovered_cycle == 1
    # stage 2 (resolver): Packages and predicted native nodes
    assert graph.get(package_id("numpy", "1.26.4")).discovered_cycle == 2
    # no RESOLVER prediction to reconcile into -> fresh PROBE-cycle (3) nodes.
    assert graph.get(syslib_id("libGL.so.1")).discovered_cycle == 3
    assert graph.get(binary_id("pg_config")).discovered_cycle == 3


def test_build_empty_repo_yields_only_test_node(tmp_path):
    (tmp_path / "app.py").write_text("import os\nimport sys\n")
    from conftest import FakeExecutor  # type: ignore

    ex = FakeExecutor(default=_r(returncode=1, stderr="x"))
    graph = build_dep_graph(str(tmp_path), ex, host_executor=ex)

    assert graph.get(TEST_NODE_ID) is not None
    assert [n for n in graph.nodes if n.type is NodeType.IMPORT] == []
    assert [n for n in graph.nodes if n.type is NodeType.PACKAGE] == []


def test_project_node_hubs_runtime_deps_and_routes_test_deps(tmp_path):
    """Project node: runtime declared deps hang off Project; test/optional deps
    hang off the Test goal; certifi gains a parent (the no-parent observation)."""
    from python_deps.depgraph.build import _add_project_node
    from python_deps.depgraph.ids import project_id
    from python_deps.depgraph.schema import (
        DepGraph,
        DiscoveredBy,
        Edge,
        EdgeType,
        Layer,
        Node,
    )

    (tmp_path / "pyproject.toml").write_text(
        '[project]\n'
        'name = "myproj"\n'
        'dependencies = ["certifi>=2020"]\n'
        '[project.optional-dependencies]\n'
        'test = ["pytest>=7"]\n'
    )
    test_node = Node(
        id=TEST_NODE_ID, type=NodeType.TEST, name="repo_tests_pass",
        layer=Layer.TESTS, discovered_by=DiscoveredBy.GOAL,
    )
    certifi = Node(
        id=package_id("certifi", "2026.1.1"), type=NodeType.PACKAGE,
        name="certifi", version="2026.1.1", layer=Layer.PIP,
        discovered_by=DiscoveredBy.RESOLVER,
    )
    pytest_pkg = Node(
        id=package_id("pytest", "8.0.0"), type=NodeType.PACKAGE, name="pytest",
        version="8.0.0", layer=Layer.PIP, discovered_by=DiscoveredBy.RESOLVER,
    )
    graph = DepGraph().with_node(test_node).with_node(certifi).with_node(pytest_pkg)

    out = _add_project_node(graph, str(tmp_path))
    pid = project_id("myproj")

    proj = out.get(pid)
    assert proj is not None and proj.type is NodeType.PROJECT
    # a pyproject.toml declares a build system -> the repo is editable-installable
    assert proj.data.get("installable") is True

    req = {(e.src, e.dst) for e in out.edges if e.relation is EdgeType.REQUIRES}
    assert (TEST_NODE_ID, pid) in req  # Test -> Project
    assert (pid, package_id("certifi", "2026.1.1")) in req  # runtime dep off Project
    assert (TEST_NODE_ID, package_id("pytest", "8.0.0")) in req  # test dep off Test
    # certifi now has a parent (no longer orphaned at the top of the layer)
    assert any(e.dst == package_id("certifi", "2026.1.1") for e in out.edges)


def test_project_node_not_installable_without_build_manifest(tmp_path):
    """A repo with neither pyproject.toml nor setup.py is NOT editable-installable
    (no `pip install -e .` line should be rendered for it)."""
    from python_deps.depgraph.build import _add_project_node
    from python_deps.depgraph.ids import project_id
    from python_deps.depgraph.schema import DepGraph, DiscoveredBy, Layer, Node

    test_node = Node(
        id=TEST_NODE_ID, type=NodeType.TEST, name="repo_tests_pass",
        layer=Layer.TESTS, discovered_by=DiscoveredBy.GOAL,
    )
    out = _add_project_node(DepGraph().with_node(test_node), str(tmp_path))
    proj = out.get(project_id(tmp_path.name))
    assert proj is not None and proj.type is NodeType.PROJECT
    assert proj.data.get("installable") is False


def test_project_node_installable_with_setup_py_only(tmp_path):
    """A legacy repo with only setup.py (no pyproject.toml) is still installable."""
    from python_deps.depgraph.build import _add_project_node
    from python_deps.depgraph.ids import project_id
    from python_deps.depgraph.schema import DepGraph, DiscoveredBy, Layer, Node

    (tmp_path / "setup.py").write_text("from setuptools import setup\nsetup(name='legacy')\n")
    test_node = Node(
        id=TEST_NODE_ID, type=NodeType.TEST, name="repo_tests_pass",
        layer=Layer.TESTS, discovered_by=DiscoveredBy.GOAL,
    )
    out = _add_project_node(DepGraph().with_node(test_node), str(tmp_path))
    proj = out.get(project_id(tmp_path.name))
    assert proj is not None and proj.data.get("installable") is True


def _project_installable(tmp_path):
    """Helper: run _add_project_node on a bare repo and return the PROJECT node's
    installable flag."""
    from python_deps.depgraph.build import _add_project_node
    from python_deps.depgraph.ids import project_id
    from python_deps.depgraph.schema import DepGraph, DiscoveredBy, Layer, Node

    test_node = Node(
        id=TEST_NODE_ID, type=NodeType.TEST, name="repo_tests_pass",
        layer=Layer.TESTS, discovered_by=DiscoveredBy.GOAL,
    )
    out = _add_project_node(DepGraph().with_node(test_node), str(tmp_path))
    return out.get(project_id(tmp_path.name)).data.get("installable")


def test_tool_config_only_pyproject_is_not_installable(tmp_path):
    """A pyproject.toml that ONLY carries tool config (no [project]/[build-system])
    is NOT a pip-installable package: a flat multi-module repo would fail
    `pip install -e .` ("Multiple top-level modules"), aborting setup.sh under
    `set -Eeuo pipefail`. Must not be flagged installable."""
    (tmp_path / "pyproject.toml").write_text(
        "[tool.black]\nline-length = 88\n\n[tool.ruff]\nselect = ['E']\n"
    )
    (tmp_path / "main.py").write_text("print('hi')\n")
    (tmp_path / "helpers.py").write_text("x = 1\n")
    assert _project_installable(tmp_path) is False


def test_pyproject_with_build_system_only_is_installable(tmp_path):
    """A [build-system] table (PEP 517 backend declared) signals installability
    even without a [project] table (metadata may live in setup.cfg)."""
    (tmp_path / "pyproject.toml").write_text(
        "[build-system]\nrequires = ['setuptools>=61']\n"
        "build-backend = 'setuptools.build_meta'\n"
    )
    assert _project_installable(tmp_path) is True


def test_tool_only_pyproject_but_setup_py_present_is_installable(tmp_path):
    """A tool-config-only pyproject does not veto a real setup.py — the repo is
    still installable via the legacy path."""
    (tmp_path / "pyproject.toml").write_text("[tool.black]\nline-length = 88\n")
    (tmp_path / "setup.py").write_text("from setuptools import setup\nsetup(name='legacy')\n")
    assert _project_installable(tmp_path) is True


def test_malformed_pyproject_without_setup_py_is_not_installable(tmp_path):
    """An unparseable pyproject with no setup.py cannot be confirmed installable
    -> not flagged (never emit a possibly-broken `-e .`)."""
    (tmp_path / "pyproject.toml").write_text("this is not [ valid toml =\n")
    assert _project_installable(tmp_path) is False


_LDD_CLOSURE = """\
numpy==1.26.4
    # via opencv-python
opencv-python==4.9.0.80
    # via -r -
"""

_CV2_SO_BUILD = (
    "/usr/local/lib/python3.11/dist-packages/cv2/cv2.cpython-311-x86_64-linux-gnu.so"
)


def test_build_ldd_probe_creates_fresh_node_without_a_prior(tmp_path):
    """Stage 4.5 is LIVE in the pipeline: when install AND import both succeed,
    ldd_probe discovers ``libGL.so.1`` from the installed binary. This
    fixture's closure carries no ``build_from_source`` signal, so
    ``seed_wheel_oracle_prior`` predicts nothing here and there is no RESOLVER
    node to reconcile into — ldd_probe creates a FRESH ``discovered_by=PROBE``
    node (soname-keyed id, apt-resolved fix-candidate via os_resolver.PROVIDER_TABLE).
    (Declaration mining, which would restore reconciliation for a repo that
    DOES declare its apt deps, is cluster 1b — deferred, not part of this
    plan.)"""
    import json

    from conftest import FakeExecutor  # type: ignore

    (tmp_path / "app.py").write_text("import cv2\n")
    # Declared-only roots: opencv-python must be declared for the closure to
    # resolve (the cv2 import audits demand but never generates a root).
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname="fx"\nversion="0"\ndependencies=["opencv-python"]\n'
    )
    ex = FakeExecutor(
        responses={
            "uv pip compile": _r(stdout=_LDD_CLOSURE),
            "pip install": _r(returncode=0),  # install SUCCEEDS
            "locate_file": _r(stdout=json.dumps({"opencv-python": [_CV2_SO_BUILD]})),
            "ldd ": _r(stdout=f"{_CV2_SO_BUILD}:\n\tlibGL.so.1 => not found\n"),
            "apt-cache show libgl1": _r(stdout="Package: libgl1\n"),
        },
        default=_r(returncode=0),
    )

    graph = build_dep_graph(
        str(tmp_path), ex, host_executor=ex, exclude_newer="2024-01-01"
    )

    assert any(c.startswith("ldd ") for c in ex.calls)

    libgl = graph.get(syslib_id("libGL.so.1"))
    assert libgl is not None
    assert libgl.discovered_by is DiscoveredBy.PROBE  # no prior to reconcile into
    assert graph.get(syslib_id("libgl1")) is None       # no apt-keyed prediction exists
    assert libgl.check_command == "ldconfig -p | grep libGL.so.1"
    assert libgl.fix_candidates == ("apt:libgl1",)
    assert (
        package_id("opencv-python", "4.9.0.80"),
        syslib_id("libGL.so.1"),
    ) in {(e.src, e.dst) for e in graph.edges}


def test_build_invokes_certified_relink_stage(tmp_path):
    """Stage 4a is wired: build runs the packages_distributions probe in the
    container, and it runs BEFORE the import probe."""
    from conftest import FakeExecutor  # type: ignore

    (tmp_path / "app.py").write_text("import dateutil\n")
    # Permissive executor: every command 'succeeds' with empty output, so the
    # pipeline runs end-to-end without crashing and we can inspect .calls.
    executor = FakeExecutor(default=_r(returncode=0))

    build_dep_graph(str(tmp_path), executor, host_executor=executor, target_python="3.11")

    relink_calls = [i for i, c in enumerate(executor.calls) if "packages_distributions" in c]
    assert relink_calls, "build_dep_graph must invoke the Stage 4a relink probe"
    relink_idx = relink_calls[0]
    import_idx = next(
        (i for i, c in enumerate(executor.calls) if 'python -c "import dateutil"' in c),
        10**9,
    )
    # Stage 4a must run before the import probe so its certified edges exist when
    # import_probe attributes gaps to owning packages.
    assert relink_idx < import_idx


def test_no_provisional_3a_link_in_build(tmp_path):
    """The provisional Stage 3a ``link_imports_to_packages`` heuristic is retired:
    certified edges (Stage 4a) are the SOLE Import->Package source in a build.

    Distinguishes the two by edge ``origin``: the Stage 3a heuristic tagged its
    edges ``origin="reconcile"``; Stage 4a tags certified edges ``origin=
    "certified"``. After removing 3a, EVERY Import->Package edge a build produces
    must be ``certified`` and NONE may be ``reconcile`` — the honest proof that
    the heuristic never ran during construction (asserting only "no 3a call"
    would pass vacuously; asserting the marker actually distinguishes them)."""
    from python_deps.depgraph.schema import EdgeType

    graph = _build(tmp_path)

    imp_pkg_edges = [
        e
        for e in graph.edges
        if e.relation is EdgeType.REQUIRES
        and (s := graph.get(e.src)) is not None
        and s.type is NodeType.IMPORT
        and (d := graph.get(e.dst)) is not None
        and d.type is NodeType.PACKAGE
    ]
    # The honest fixture map certifies cv2->opencv-python and PIL->Pillow.
    assert imp_pkg_edges, "expected certified Import->Package edges from Stage 4a"
    assert all(e.origin == "certified" for e in imp_pkg_edges)
    # The retired Stage 3a heuristic marker must never appear.
    assert not any(e.origin == "reconcile" for e in imp_pkg_edges)


# --------------------------------------------------------------------------- #
# Task 8 — targeted extras: build_dep_graph threads needed_extras into both
# select_roots and resolve_closure (the seam cluster-1 discovery will source).
# --------------------------------------------------------------------------- #
def test_build_dep_graph_threads_needed_extras_into_roots_and_resolve(tmp_path):
    from unittest.mock import patch

    import python_deps.depgraph.build as build_mod

    ex = _make_executor()
    calls: dict = {}
    orig_select_roots = build_mod.select_roots
    orig_resolve_closure = build_mod.resolve_closure

    def spy_select_roots(repo_path, graph, needed_extras=frozenset(), **kwargs):
        calls["select_roots_needed_extras"] = needed_extras
        return orig_select_roots(
            repo_path, graph, needed_extras=needed_extras, **kwargs
        )

    def spy_resolve_closure(*args, **kwargs):
        calls["resolve_closure_extras"] = kwargs.get("extras")
        return orig_resolve_closure(*args, **kwargs)

    with patch.object(build_mod, "select_roots", side_effect=spy_select_roots), patch.object(
        build_mod, "resolve_closure", side_effect=spy_resolve_closure
    ):
        build_dep_graph(
            _make_repo(tmp_path), ex, host_executor=ex, needed_extras=frozenset({"test"})
        )

    assert calls["select_roots_needed_extras"] == frozenset({"test"})
    assert calls["resolve_closure_extras"] == frozenset({"test"})


def test_build_dep_graph_default_needed_extras_is_runtime_only(tmp_path):
    # NOTE (Task 4): this asserts the `needed_extras` VALUE build.py passes to
    # select_roots, not the overall root-selection SCOPE. Since Task 4,
    # select_roots's default scope is testability (runtime + dev/test groups +
    # evidence.used_extras), not "runtime only" -- but the `needed_extras`
    # feature-extras override that build.py forwards absent a caller override
    # is still empty, which is exactly what this test checks.
    from unittest.mock import patch

    import python_deps.depgraph.build as build_mod

    ex = _make_executor()
    calls: dict = {}
    orig_select_roots = build_mod.select_roots

    def spy_select_roots(repo_path, graph, needed_extras=frozenset(), **kwargs):
        calls["select_roots_needed_extras"] = needed_extras
        return orig_select_roots(
            repo_path, graph, needed_extras=needed_extras, **kwargs
        )

    with patch.object(build_mod, "select_roots", side_effect=spy_select_roots):
        build_dep_graph(_make_repo(tmp_path), ex, host_executor=ex)

    # No caller override -> the needed_extras (feature-extras) override passed
    # to select_roots is empty, NOT a union of every declared
    # optional-dependencies group. (Dev/test groups are still default-included
    # by select_roots's own testability-scope policy -- see roots.py.)
    assert calls["select_roots_needed_extras"] == frozenset()


# --------------------------------------------------------------------------- #
# P1.4 — Phase-A repair fixpoint full-arm smoke. The SAME cv2/PIL/psycopg2 repo,
# but UNDER-DECLARED (no pyproject: zero declared roots). The scanned imports
# audit missing against the empty closure and the fixpoint repairs each to its
# distribution (RECORD-grounded via an injected fake provider), converging to the
# same Package nodes — now discovered_by=AUDIT, not RESOLVER. (P0.1's declared
# test above is untouched; this is a separate under-declared fixture.)
# --------------------------------------------------------------------------- #
def test_build_repairs_under_declared_repo_via_fixpoint(tmp_path):
    from conftest import SequencedFakeExecutor  # type: ignore

    from python_deps.depgraph.schema import DiscoveredBy as _DB
    from python_deps.import_mapping import normalize_package_name as _norm

    (tmp_path / "app.py").write_text(
        "import os\nimport cv2\nfrom PIL import Image\nimport psycopg2\n"
    )
    # NO pyproject.toml -> no manifest-declared roots. Repair is the only path
    # that can populate the Package layer here.
    round1 = (
        "numpy==1.26.4\n    # via opencv-python\n"
        "opencv-python==4.9.0.80\n    # via -r -\n"
        "Pillow==10.3.0\n    # via -r -\n"
        "psycopg2==2.9.9\n    # via -r -\n"
    )
    ex = SequencedFakeExecutor(
        responses={
            "uv lock": [_r(1, stderr="lock unavailable")],
            "uv pip compile": [_r(stdout=round1)],
            "pip install": [_r(0)],
        },
        default=_r(0),
    )
    provided = {"opencv-python": {"cv2"}, "Pillow": {"PIL"}, "psycopg2": {"psycopg2"}}
    norm = {_norm(k): v for k, v in provided.items()}
    provider = lambda dist: norm.get(_norm(dist))  # noqa: E731

    graph = build_dep_graph(
        str(tmp_path), ex, host_executor=ex, record_provider=provider
    )

    for dist, ver in (
        ("opencv-python", "4.9.0.80"),
        ("Pillow", "10.3.0"),
        ("psycopg2", "2.9.9"),
    ):
        node = graph.get(package_id(dist, ver))
        assert node is not None, f"{dist} package missing after repair"
        assert node.discovered_by is _DB.AUDIT, f"{dist} should be AUDIT-discovered"
    # A transitive dep pulled in by a repaired root stays RESOLVER (not AUDIT).
    numpy = graph.get(package_id("numpy", "1.26.4"))
    assert numpy is not None and numpy.discovered_by is DiscoveredBy.RESOLVER


